# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rubocop", "1.25.0"
gem "rubocop-performance", "~> 1.13"
gem "rubocop-rspec", "~> 2.8"
gem "standard", "~> 1.7"

gem "activerecord", "~> 6.1"
gem "pg", "~> 1.3"
gem "standalone_migrations", "~> 6.1"

# gem "que", "~> 1.0"
gem "que", github: "que-rb/que", ref: "refs/pull/319/head" # TODO: currently required for ruby 3 support
gem "que-scheduler", "~> 4.2"
gem "que-web", "~> 0.9.3"

gem "puma", "~> 5.6"
