# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "guard-rspec", "~> 4.7"
gem "rubocop", "1.25.0"
gem "rubocop-performance"
gem "rubocop-rspec"

gem "standard", "~> 1.7"

gem "pry", "~> 0.14.1"

gem "numbers_in_words", "~> 1.0"
