# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "capybara", "~> 3.36"
gem "selenium-webdriver", "~> 4.1"
gem "webdrivers", "~> 5.0"

gem "pry", "~> 0.14.1"
